---
title: 'Part 1: stringr functions'
author: "Kirsten Hodgson"
date: "2/17/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

### Detect string patterns with `str_detect()`

```{r}
vec <- c(" A Unicorn    Fish ", "add   cornmeal", "French fries  and ", "Acorn SQUASH")

str_detect(vec, pattern = "corn")
```

```{r}
walk_subset <- starwars %>% 
  filter(str_detect(name, pattern = "walk"))

#Use str_subset() to combine filter and str_detect
```

### Replace a string pattern with something else

`str_replace()` to replace an existing string pattern

```{r}
vec_bren <- str_replace(vec, pattern = "corn", replacement = "COOL")

vec_bren
```

replace the pattern "Sky" with the pattern "TORNADO"

```{r}
sw_tornado <- starwars %>% 
  mutate(name = str_replace(name, pattern = "Sky", replacement = "TORNADO"))
```

### Use `str_trim()` to remove excess leading and trailing white space

```{r}
str_trim(vec)
```

### Use `str_squish()` to remove all excess whitespace

```{r}
str_squish(vec)
```

### Use `str_to_*()` to convert case

```{r}
str_to_lower(vec)
str_to_upper(vec)
str_to_title(vec)
```

### Using these in combination

```{r}
sw_combo <- starwars %>% 
  filter(str_detect(name, pattern = "Darth")) %>% 
  mutate(name = str_replace(name, pattern = "Darth", replacement = "LLAMA")) %>% 
  mutate(name = str_to_lower(name))
```

